// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackGestaoDeHospital.DataBase;

#nullable disable

namespace StackGestaoDeHospital.DataBase.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260531153604_CorrecaoAtendimento")]
    partial class CorrecaoAtendimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GESTAOHOSPITAL")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicoEspecialidade", b =>
                {
                    b.Property<int>("EspecialidadesId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("EspecialidadesId", "MedicoId");

                    b.HasIndex("MedicoId");

                    b.ToTable("MedicoEspecialidade", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EnfermeiroId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Queixa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnfermeiroId");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Atendimento", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamento", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Especialidade", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Pessoa", "GESTAOHOSPITAL");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Funcionario", b =>
                {
                    b.HasBaseType("StackGestaoDeHospital.Model.Pessoa");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasFilter("[Matricula] IS NOT NULL");

                    b.ToTable("Funcionario", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Paciente", b =>
                {
                    b.HasBaseType("StackGestaoDeHospital.Model.Pessoa");

                    b.Property<string>("NumeroCarteirinha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlanoSaude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Paciente", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Enfermeiro", b =>
                {
                    b.HasBaseType("StackGestaoDeHospital.Model.Funcionario");

                    b.Property<string>("CRE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("CRE")
                        .IsUnique()
                        .HasFilter("[CRE] IS NOT NULL");

                    b.ToTable("Enfermeiro", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Medico", b =>
                {
                    b.HasBaseType("StackGestaoDeHospital.Model.Funcionario");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("CRM")
                        .IsUnique()
                        .HasFilter("[CRM] IS NOT NULL");

                    b.ToTable("Medico", "GESTAOHOSPITAL");
                });

            modelBuilder.Entity("MedicoEspecialidade", b =>
                {
                    b.HasOne("StackGestaoDeHospital.Model.Especialidade", null)
                        .WithMany()
                        .HasForeignKey("EspecialidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackGestaoDeHospital.Model.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Atendimento", b =>
                {
                    b.HasOne("StackGestaoDeHospital.Model.Enfermeiro", "Enfermeiro")
                        .WithMany()
                        .HasForeignKey("EnfermeiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackGestaoDeHospital.Model.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackGestaoDeHospital.Model.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackGestaoDeHospital.Model.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enfermeiro");

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Funcionario", b =>
                {
                    b.HasOne("StackGestaoDeHospital.Model.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("StackGestaoDeHospital.Model.Funcionario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Paciente", b =>
                {
                    b.HasOne("StackGestaoDeHospital.Model.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("StackGestaoDeHospital.Model.Paciente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Enfermeiro", b =>
                {
                    b.HasOne("StackGestaoDeHospital.Model.Funcionario", null)
                        .WithOne()
                        .HasForeignKey("StackGestaoDeHospital.Model.Enfermeiro", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackGestaoDeHospital.Model.Medico", b =>
                {
                    b.HasOne("StackGestaoDeHospital.Model.Funcionario", null)
                        .WithOne()
                        .HasForeignKey("StackGestaoDeHospital.Model.Medico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
